#pragma once
#include <chrono>
#include <cstdlib>
#include <functional>
#include <memory>
#include <print>
#include <random>
#include <thread>
#include <boost/locale.hpp>
#define NOMINMAX
#include <Windows.h>
#include <conio.h>